#!/usr/bin/env python3
"""
build_data.py — regenerate data/editions.js from assets/plots/*.svg

Edit the META table below to add an edition or change pricing/Japanese name,
then run:  python tools/build_data.py
"""
import os, re, json

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
PLOTS = os.path.join(ROOT, "assets", "plots")
OUT = os.path.join(ROOT, "data", "editions.js")

# key -> metadata. `file` is the svg basename in assets/plots (without .svg).
META = {
 "zaku":     {"file":"zaku-ii",  "name":"Zaku II",  "code":"MS-06",     "jp":"ザク",                 "edition":"ED. 09/25 · 11×14″", "price":"$45"},
 "guncannon":{"file":"guncannon","name":"Guncannon","code":"RX-77",     "jp":"ガンキャノン",          "edition":"ED. 18/25 · 11×14″", "price":"$45"},
 "bigzam":   {"file":"big-zam",  "name":"Big Zam",  "code":"MA-08",     "jp":"ビグ・ザム",            "edition":"ED. 05/25 · 11×14″", "price":"$45"},
 "dom":      {"file":"dom",      "name":"Dom",      "code":"MS-09",     "jp":"ドム",                 "edition":"ED. 12/25 · 11×14″", "price":"$45"},
 "zgok":     {"file":"zgok",     "name":"Z'Gok",    "code":"MSM-07",    "jp":"ズゴック",              "edition":"ED. 22/25 · 11×14″", "price":"$45"},
 "gp02":     {"file":"gp-02",    "name":"GP-02A",   "code":"RX-78GP02", "jp":"ガンダム試作2号機",     "edition":"ED. 15/25 · 11×14″", "price":"$45"},
 "gm":       {"file":"gm",       "name":"GM",       "code":"RGM-79",    "jp":"ジム",                 "edition":"ED. 07/25 · 11×14″", "price":"$45"},
 "guntank":  {"file":"guntank",  "name":"Guntank",  "code":"RX-75",     "jp":"ガンタンク",            "edition":"ED. 11/25 · 11×14″", "price":"$45"},
}

# Short editorial blurb shown on each edition's product page.
LORE = {
 "zaku":     "The workhorse of the Principality of Zeon — mass-produced and instantly known by its single mono-eye and shoulder spike. More Zaku IIs saw combat in the One Year War than any other mobile suit.",
 "guncannon":"A mid-range support unit of the Earth Federation, built around its shoulder-mounted cannons. Heavier armor traded mobility for firepower fighting alongside the RX-78.",
 "bigzam":   "A colossal Zeon mobile armor designed for base defense, shielded by an I-field that turned aside beam weapons. A single unit was meant to hold off an entire fleet.",
 "dom":      "A ground-assault suit riding hover thrusters for deceptively fast movement across open terrain. Its scattering beam gun and giant heat saber made it a frontline terror.",
 "zgok":     "An amphibious Zeon suit built for hit-and-run raids from the water. Rounded armor, clawed manipulators, and head-mounted mega particle guns.",
 "gp02":     "A Gundam Development Project unit engineered to carry and fire a tactical warhead. Heavy shielding and a massive plasma-clad shield define its silhouette.",
 "gm":       "The Federation's answer to mass production — a simplified, mass-deployable Gundam derivative that turned the tide through sheer numbers.",
 "guntank":  "Half mobile suit, half tank. A tracked lower body and twin long-range cannons made it the artillery support of the Federation's early V-Project.",
}

# order of the dropdown in the live plotter, and of the cards in the shop grid
PLOTTER_ORDER = ["zaku","dom","guncannon","bigzam","zgok","gp02","gm","guntank"]
SHOP_ORDER    = ["zaku","guncannon","bigzam","dom","zgok","gp02","gm","guntank"]

def extract(file):
    s = open(os.path.join(PLOTS, file + ".svg")).read()
    vb = re.search(r"viewBox='([^']*)'", s).group(1).split()
    d  = re.search(r"d='([^']*)'", s).group(1)
    return int(vb[2]), int(vb[3]), d

suits = {}
for k, m in META.items():
    w, h, d = extract(m["file"])
    suits[k] = {"name":m["name"], "code":m["code"], "jp":m["jp"],
                "edition":m["edition"], "price":m["price"], "lore":LORE.get(k, ""),
                "file":m["file"]+".svg", "w":w, "h":h, "d":d}

data = {"suits":suits, "plotterOrder":PLOTTER_ORDER, "shopOrder":SHOP_ORDER}
with open(OUT, "w") as f:
    f.write("/* AUTO-GENERATED by tools/build_data.py — edit assets/plots/*.svg + META then regenerate. */\n")
    f.write("window.PLOTFLOW = " + json.dumps(data, ensure_ascii=False, indent=0) + ";\n")
print("wrote", OUT, "with", len(suits), "editions")
