#!/usr/bin/env python3
"""
build_data.py: regenerate data/editions.js from assets/plots/*.svg

Edit the META table below to add an edition or change pricing/Japanese name,
then run:  python tools/build_data.py
"""
import os, re, json

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
PLOTS = os.path.join(ROOT, "assets", "plots")
OUT = os.path.join(ROOT, "data", "editions.js")

# key -> metadata. `file` is the svg basename in assets/plots (without .svg).
META = {
 "zaku":     {"file":"zaku-ii",  "name":"Zaku II",  "code":"MS-06",     "jp":"ザク",                 "edition":"STUDY · 11×14″", "price":"$45"},
 "guncannon":{"file":"guncannon","name":"Guncannon","code":"RX-77",     "jp":"ガンキャノン",          "edition":"STUDY · 11×14″", "price":"$45"},
 "bigzam":   {"file":"big-zam",  "name":"Big Zam",  "code":"MA-08",     "jp":"ビグ・ザム",            "edition":"STUDY · 11×14″", "price":"$45"},
 "dom":      {"file":"dom",      "name":"Dom",      "code":"MS-09",     "jp":"ドム",                 "edition":"STUDY · 11×14″", "price":"$45"},
 "zgok":     {"file":"zgok",     "name":"Z'Gok",    "code":"MSM-07",    "jp":"ズゴック",              "edition":"STUDY · 11×14″", "price":"$45"},
 "gp02":     {"file":"gp-02",    "name":"GP-02A",   "code":"RX-78GP02", "jp":"ガンダム試作2号機",     "edition":"STUDY · 11×14″", "price":"$45"},
}

# Short editorial blurb shown on each edition's product page + lore card.
# Accurate to Universal Century canon. Keep to ~6 lines so it fits the card.
LORE = {
 "zaku":     "The workhorse of the Principality of Zeon, the suit that proved the mobile-suit weapon class in combat. Instantly known by its single mono-eye and shoulder spike, more Zaku IIs fought in the One Year War (U.C. 0079) than any other machine. Char Aznable's crimson command type moved at three times the normal speed, earning him the name Red Comet.",
 "guncannon":"One of the Earth Federation's first mass-production mobile suits, developed under Project V alongside the RX-78 Gundam. Built around twin shoulder cannons for mid- and long-range fire support, it traded mobility for heavier armor and served aboard White Base through the One Year War.",
 "bigzam":   "A colossal Zeon mobile armor built for base defense, its I-field barrier turning aside beam weapons while banks of mega particle guns swept the field. A single unit was meant to hold off an entire fleet. Dozle Zabi took it into the defense of Solomon in the war's final days.",
 "dom":      "A Zeon ground-assault suit that skated across open terrain on thermonuclear hover jets, deceptively fast for its bulk. Armed with a scattering beam gun and a giant heat saber, its Rick Dom variants armed the Black Tri-Stars and their feared Jet Stream Attack.",
 "zgok":     "An amphibious Zeon suit built for hit-and-run raids from the water. Rounded armor, iron-nail claws, and head-mounted mega particle guns made it deadly at close range. Char Aznable fielded a custom command type in his signature red.",
 "gp02":     "A Gundam Development Project prototype engineered around a single purpose: to carry and fire a tactical nuclear warhead. Heavy shielding and a massive plasma-clad shield define its silhouette. In U.C. 0083 it was stolen by Anavel Gato, the Nightmare of Solomon.",
}

# order of the dropdown in the live plotter, and of the cards in the shop grid
PLOTTER_ORDER = ["zaku","dom","guncannon","bigzam","zgok","gp02"]
SHOP_ORDER    = ["zaku","guncannon","bigzam","dom","zgok","gp02"]

def extract(file):
    s = open(os.path.join(PLOTS, file + ".svg")).read()
    vb = re.search(r"viewBox='([^']*)'", s).group(1).split()
    d  = re.search(r"d='([^']*)'", s).group(1)
    return int(vb[2]), int(vb[3]), d

suits = {}
for k, m in META.items():
    w, h, d = extract(m["file"])
    suits[k] = {"name":m["name"], "code":m["code"], "jp":m["jp"],
                "edition":m["edition"], "price":m["price"], "lore":LORE.get(k, ""),
                "file":m["file"]+".svg", "w":w, "h":h, "d":d}

data = {"suits":suits, "plotterOrder":PLOTTER_ORDER, "shopOrder":SHOP_ORDER}
with open(OUT, "w") as f:
    f.write("/* AUTO-GENERATED by tools/build_data.py: edit assets/plots/*.svg + META then regenerate. */\n")
    f.write("window.PLOTFLOW = " + json.dumps(data, ensure_ascii=False, indent=0) + ";\n")
print("wrote", OUT, "with", len(suits), "editions")
