#!/usr/bin/env python3
"""
build_data.py — regenerate data/editions.js from assets/plots/*.svg

Edit the META table below to add an edition or change pricing/Japanese name,
then run:  python tools/build_data.py
"""
import os, re, json

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
PLOTS = os.path.join(ROOT, "assets", "plots")
OUT = os.path.join(ROOT, "data", "editions.js")

# key -> metadata. `file` is the svg basename in assets/plots (without .svg).
META = {
 "zaku":     {"file":"zaku-ii",  "name":"Zaku II",  "code":"MS-06",     "jp":"ザク",                 "edition":"ED. 09/25 · A2", "price":"$30"},
 "guncannon":{"file":"guncannon","name":"Guncannon","code":"RX-77",     "jp":"ガンキャノン",          "edition":"ED. 18/25 · A3", "price":"$30"},
 "bigzam":   {"file":"big-zam",  "name":"Big Zam",  "code":"MA-08",     "jp":"ビグ・ザム",            "edition":"ED. 05/25 · A1", "price":"$30"},
 "dom":      {"file":"dom",      "name":"Dom",      "code":"MS-09",     "jp":"ドム",                 "edition":"ED. 12/25 · A2", "price":"$30"},
 "zgok":     {"file":"zgok",     "name":"Z'Gok",    "code":"MSM-07",    "jp":"ズゴック",              "edition":"ED. 22/25 · A3", "price":"$30"},
 "gp02":     {"file":"gp-02",    "name":"GP-02A",   "code":"RX-78GP02", "jp":"ガンダム試作2号機",     "edition":"ED. 15/25 · A2", "price":"$30"},
 "gm":       {"file":"gm",       "name":"GM",       "code":"RGM-79",    "jp":"ジム",                 "edition":"ED. 07/25 · A3", "price":"$30"},
 "guntank":  {"file":"guntank",  "name":"Guntank",  "code":"RX-75",     "jp":"ガンタンク",            "edition":"ED. 11/25 · A2", "price":"$30"},
}

# order of the dropdown in the live plotter, and of the cards in the shop grid
PLOTTER_ORDER = ["zaku","dom","guncannon","bigzam","zgok","gp02","gm","guntank"]
SHOP_ORDER    = ["zaku","guncannon","bigzam","dom","zgok","gp02"]

def extract(file):
    s = open(os.path.join(PLOTS, file + ".svg")).read()
    vb = re.search(r"viewBox='([^']*)'", s).group(1).split()
    d  = re.search(r"d='([^']*)'", s).group(1)
    return int(vb[2]), int(vb[3]), d

suits = {}
for k, m in META.items():
    w, h, d = extract(m["file"])
    suits[k] = {"name":m["name"], "code":m["code"], "jp":m["jp"],
                "edition":m["edition"], "price":m["price"],
                "file":m["file"]+".svg", "w":w, "h":h, "d":d}

data = {"suits":suits, "plotterOrder":PLOTTER_ORDER, "shopOrder":SHOP_ORDER}
with open(OUT, "w") as f:
    f.write("/* AUTO-GENERATED by tools/build_data.py — edit assets/plots/*.svg + META then regenerate. */\n")
    f.write("window.PLOTFLOW = " + json.dumps(data, ensure_ascii=False, indent=0) + ";\n")
print("wrote", OUT, "with", len(suits), "editions")
